
# @Jahid Hasan Emon                                                                              
# @SID : 001360753-7                                                                             
                                                                                                 
# Project    : Designing and Devoloping London Underorund Trains Map and Operations.             
# Task 3     : Journey Planner Based on Number of Stops                                          
# SubTask 3A : Manual code exicution first (Demo Code)                                           
                                                                                                 
# Procedure :                                                                                    
# We Represent stations as numbers for simplicity. Here A is station 0, B is station 1, etc.     
#                      A(0)                                                                       
#                     /   \                                                                      
#                   B(1)  C(2)                                                                   
#                     \   /                                                                      
#                     D(3)                                                                        
#                      |                                                                          
#                     E(4)                                                                        
# We call AdjacencyListGraph to stores connections (edges) between stations. We add Connections  
# in both direction, it will be an undirected graph. We call BFS for exploring stations level by 
# level and find shortest path in terms of number of stops. We call print_path to reconstruct    
# the path as it will use parent array generated by BFS to backtrack from destination to source. 





# Imports from CLRS `library` 
from adjacency_list_graph import AdjacencyListGraph
from bfs import bfs
from print_path import print_path

card_V = 5                                      # number of stations (Vertices)
G = AdjacencyListGraph(card_V, directed=False)  # We create an undirected Graph

G.insert_edge(0, 1)  # A - B           # defines an edge between station A and B and   A(0)
G.insert_edge(0, 2)  # A - C           # Connects station 0 and 2 by A-C              /   \
G.insert_edge(1, 3)  # B - D                                                        B(1)  C(2)
G.insert_edge(2, 3)  # C - D
G.insert_edge(3, 4)  # D - E

# This performs BFS Search from StartNode to EndNode 
source_station = 0  #StartNode
dest_station   = 3  #EndNode 
# dist = distance array, pi = parent array (parent" node used to rebuild the path)
dist, pi = bfs(G, source_station)      

# print_path() walks backward from destination to source using the predecessor list (pi)
# Here lambda i:i used to print station indices directly
path = print_path(pi, source_station, dest_station, lambda i:i)

print("\n=== Task 3A: Fewest Stops and Shortest Path === ")

if path is None:                                # If not path found
    print("No route found between stations.")   
else:                                           # Else we print the path and total stops
    print(f"The Shortest path in between station {source_station} and {dest_station} is :", path)
    print("Total number of stops:", dist[dest_station])
